#ifndef DEBUG_GRAPH_DEF_PAIR_TEST_RANDOM
#define DEBUG_GRAPH_DEF_PAIR_TEST_RANDOM

#undef __IS_DIRECTED
#undef __IS_DIFF_MODE

#define  __IS_DIRECTED 1
#define __IS_DIFF_MODE 1

#endif // DEBUG_GRAPH_DEF_PAIR_TEST_RANDOM
